export type Product = {
  rank: number;
  name: string;
  slug: string;
  url: string;
  category: string;
  score: number;
  verdict: string;
  delta?: number;
  description?: string;
  strengths?: string[];
  weaknesses?: string[];
};

export const CATEGORIES = [
  "All",
  "SaaS",
  "Consumer",
  "Fintech",
  "E-commerce",
  "Health",
  "Productivity",
  "Developer Tools",
  "Media",
];

export const SORT_OPTIONS = [
  { value: "rank", label: "Rank" },
  { value: "score-desc", label: "Highest score" },
  { value: "score-asc", label: "Lowest score" },
  { value: "movers", label: "Biggest movers" },
  { value: "name", label: "A–Z" },
];

/* ── Seed list ── */
const RAW_PRODUCTS: Omit<Product, "rank">[] = [
  {
    name: "Linear",
    slug: "linear",
    url: "linear.app",
    category: "SaaS",
    score: 4.3,
    verdict: "The standard for modern SaaS interaction design",
    delta: 0.2,
    description: "Linear has become the benchmark that other developer tools measure themselves against. The interface is fast — not marketing-fast, but perceptibly instant. Every interaction feels like it was designed by someone who uses the product daily. The keyboard-first philosophy isn't a gimmick; it's woven into every workflow. Where most project management tools add features by adding screens, Linear adds features by making existing screens smarter.",
    strengths: [
      "Sub-100ms response on every interaction",
      "Keyboard shortcuts that form a coherent language",
      "Information density without visual clutter",
      "Consistent component patterns across every view",
      "Onboarding that teaches by doing, not by touring",
    ],
    weaknesses: [
      "Mobile experience trails desktop significantly",
      "Reporting and analytics feel like an afterthought",
      "Custom workflows limited compared to legacy tools",
    ],
  },
  {
    name: "Notion",
    slug: "notion",
    url: "notion.so",
    category: "Productivity",
    score: 4.1,
    verdict: "Flexible power with a learning curve that still rewards",
    delta: 0.1,
    description: "Notion took the radical bet that one tool could replace many — and largely won. The block-based editor is genuinely flexible, and the database system enables workflows that would require three other tools. The learning curve is real, but the payoff is a workspace that shapes itself around how you think. The gap between 'getting started' and 'getting productive' is where Notion still loses people.",
    strengths: [
      "Block-based editing that actually works",
      "Database views that replace spreadsheets and project tools",
      "Template ecosystem that accelerates new users",
      "Collaboration features woven into every element",
      "API that enables serious integrations",
    ],
    weaknesses: [
      "Performance degrades with large workspaces",
      "Blank-page syndrome for new users",
      "Search is functional but not fast enough for power users",
    ],
  },
  {
    name: "Stripe Dashboard",
    slug: "stripe",
    url: "dashboard.stripe.com",
    category: "Fintech",
    score: 4.0,
    verdict: "Complexity made legible — developer-grade clarity for finance",
    description: "Stripe's dashboard handles an extraordinary amount of complexity — payments, subscriptions, invoicing, fraud detection, tax compliance — and makes most of it navigable. The information architecture is remarkably clear for the density of data presented. Where it falls short of a higher score is in progressive disclosure; some workflows still require too many clicks to reach critical information.",
    strengths: [
      "Information architecture handles massive complexity",
      "Developer-oriented precision in every data display",
      "Consistent visual language across dozens of product surfaces",
      "Documentation integrated directly into the interface",
    ],
    weaknesses: [
      "Dense navigation requires familiarity to be efficient",
      "Some advanced features buried under too many layers",
      "Mobile dashboard is severely limited",
    ],
  },
  {
    name: "Vercel",
    slug: "vercel",
    url: "vercel.com",
    category: "Developer Tools",
    score: 3.9,
    verdict: "Deploy-to-delight pipeline built into every interaction",
    delta: 0.3,
    description: "Vercel has turned deployment into a design problem and solved it with taste. The dashboard communicates complex infrastructure states — builds, domains, environments, logs — through a visual language that feels calm even when things go wrong. The biggest delta this quarter reflects their investment in making the analytics and monitoring surfaces match the quality of the deploy experience.",
    strengths: [
      "Deployment feedback loop is best-in-class",
      "Error states are informative, not alarming",
      "Visual design creates calm in a domain that's usually noisy",
      "Integration ecosystem feels native, not bolted on",
    ],
    weaknesses: [
      "Pricing transparency could be clearer in the UI",
      "Log exploration still requires too much context-switching",
    ],
  },
  {
    name: "Figma",
    slug: "figma",
    url: "figma.com",
    category: "Productivity",
    score: 3.9,
    verdict: "Collaboration as a first-class design primitive",
    description: "Figma proved that design tools could be multiplayer. The real-time collaboration isn't a feature — it's the foundation everything else is built on. The plugin ecosystem, component system, and prototyping tools are all strong. Where Figma loses points is in the growing complexity of its own interface; features added since the Adobe acquisition attempt have started to create navigation overhead.",
    strengths: [
      "Real-time collaboration that actually works at scale",
      "Component and variant system enables true design systems",
      "Plugin ecosystem extends capability without bloating the core",
      "Auto-layout is the best spatial reasoning tool in any design app",
    ],
    weaknesses: [
      "Interface complexity growing with each major release",
      "Dev mode handoff still requires too many clicks",
      "Prototyping is capable but not intuitive for complex interactions",
    ],
  },
  {
    name: "Arc Browser",
    slug: "arc",
    url: "arc.net",
    category: "Consumer",
    score: 3.8,
    verdict: "Rethinks the browser chrome with taste and restraint",
    delta: -0.1,
    description: "Arc made the bold bet that the browser's frame — the chrome around the web — deserved a complete rethink. Spaces, Boosts, and the sidebar model genuinely improve how you organize browsing. The slight downward movement reflects stability issues in recent updates and the tension between innovation and reliability in a tool people depend on every minute of the day.",
    strengths: [
      "Sidebar navigation is genuinely better than tab bars",
      "Spaces concept maps to how people actually work",
      "Visual refinement and attention to detail throughout",
      "Little Arc is a clever rethinking of quick lookups",
    ],
    weaknesses: [
      "Stability issues in recent releases",
      "Memory usage higher than competitors",
      "Learning curve for users coming from traditional browsers",
    ],
  },
  {
    name: "Raycast",
    slug: "raycast",
    url: "raycast.com",
    category: "Productivity",
    score: 3.8,
    verdict: "Speed is the feature — every interaction under 200ms",
    description: "Raycast treats speed as its core design principle, and it shows. Every interaction — launching, searching, executing — feels instantaneous. The extension ecosystem turns it from a launcher into a command center. Where it excels is making complex workflows feel like one step. Where it struggles is in discoverability; the power is there, but finding it requires exploration.",
    strengths: [
      "Perceptive speed across every interaction",
      "Extension ecosystem that replaces entire apps",
      "Keyboard-driven design that never forces you to reach for the mouse",
      "AI integration that feels additive, not gimmicky",
    ],
    weaknesses: [
      "Discoverability of advanced features requires exploration",
      "Settings UI doesn't match the polish of the main experience",
      "Onboarding undersells the product's capability",
    ],
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    url: "airbnb.com",
    category: "E-commerce",
    score: 3.7,
    verdict: "Emotional design that makes browsing feel like discovery",
    description: "Airbnb remains one of the strongest examples of emotional design in production. Browsing listings feels like exploring, not shopping. The map integration, photo presentation, and pricing transparency create a flow that's genuinely enjoyable. The booking flow is solid. Where points are lost: the host-side experience and the growing number of fees that erode trust at checkout.",
    strengths: [
      "Photography-first design creates emotional connection",
      "Map and list views complement each other perfectly",
      "Search refinement is powerful without being overwhelming",
      "Category browsing (Icons, OMG!, etc.) drives genuine discovery",
    ],
    weaknesses: [
      "Fee structure creates sticker shock at checkout",
      "Host management tools trail the guest experience",
      "Review system is increasingly gamed",
    ],
  },
  {
    name: "Superhuman",
    slug: "superhuman",
    url: "superhuman.com",
    category: "Productivity",
    score: 3.8,
    verdict: "Speed and keyboard-first design justify the premium",
    description: "Superhuman proved that email — the most commoditized software category — could be reimagined through speed and intentional design constraints. The keyboard-first model, combined with AI features that actually save time, creates an experience that makes free alternatives feel sluggish. The premium pricing is justified by the time saved.",
    strengths: [
      "Email speed that makes alternatives feel broken",
      "Keyboard shortcuts that form muscle memory within days",
      "AI triage that genuinely reduces inbox processing time",
      "Visual design that's restrained and confident",
    ],
    weaknesses: [
      "Price point limits adoption and team buy-in",
      "Calendar integration still playing catch-up",
      "Limited customization compared to traditional clients",
    ],
  },
  {
    name: "Apple Music",
    slug: "apple-music",
    url: "music.apple.com",
    category: "Media",
    score: 3.6,
    verdict: "Beautiful surfaces but navigation still costs effort",
    description: "Apple Music is visually polished — every screen feels considered and premium. The typography, album art presentation, and spatial audio features are best-in-class. But navigation remains the weak point. Finding your library, managing playlists, and discovering new music all require more taps and more memory than they should. Beauty without friction reduction caps the score.",
    strengths: [
      "Visual design and typography set the standard for media apps",
      "Spatial audio implementation is genuinely immersive",
      "Integration with Apple ecosystem creates seamless device switching",
    ],
    weaknesses: [
      "Library management requires too many taps",
      "Discovery algorithms trail Spotify significantly",
      "Navigation model is inconsistent across sections",
    ],
  },
  {
    name: "Shopify Admin",
    slug: "shopify",
    url: "admin.shopify.com",
    category: "E-commerce",
    score: 3.6,
    verdict: "Enterprise complexity compressed into merchant-friendly flows",
    description: "Shopify's admin panel manages an absurd amount of functionality — inventory, orders, shipping, analytics, marketing, apps — and keeps it navigable for merchants who aren't technical. The progressive disclosure model works: simple stores see simple tools, complex stores unlock complexity. The Polaris design system ensures consistency across a massive surface area.",
    strengths: [
      "Progressive disclosure matches complexity to merchant maturity",
      "Polaris design system ensures remarkable consistency",
      "App ecosystem integrates without feeling foreign",
      "Mobile admin is surprisingly capable",
    ],
    weaknesses: [
      "Analytics and reporting still feel basic",
      "Theme customization has a steep learning curve",
      "Checkout customization is unnecessarily restricted",
    ],
  },
  {
    name: "Duolingo",
    slug: "duolingo",
    url: "duolingo.com",
    category: "Consumer",
    score: 3.6,
    verdict: "Gamification done right — habit loops that actually teach",
    description: "Duolingo cracked the code on making daily practice feel like play rather than homework. The streak system, hearts model, and progression mechanics create genuine engagement. The visual design is playful without being childish. Where it falls short of a higher score: the actual language learning effectiveness plateaus for intermediate learners, and the monetization pressure has increased.",
    strengths: [
      "Gamification that drives real habit formation",
      "Visual design that's playful and motivating",
      "Onboarding that gets users to their first lesson in under a minute",
      "Daily engagement mechanics that actually work",
    ],
    weaknesses: [
      "Learning effectiveness plateaus at intermediate levels",
      "Monetization pressure increasingly interrupts the experience",
      "Limited depth for serious language learners",
    ],
  },
  {
    name: "GitHub",
    slug: "github",
    url: "github.com",
    category: "Developer Tools",
    score: 3.5,
    verdict: "Dense but navigable — information architecture does the heavy lifting",
    description: "GitHub manages an enormous information space — code, issues, pull requests, actions, packages, discussions — and keeps it usable through strong information architecture rather than visual simplicity. It's dense by necessity. The score reflects that density is well-managed but rarely delightful; most workflows are functional and efficient without ever feeling effortless.",
    strengths: [
      "Information architecture handles massive scale",
      "Code review workflow is the industry standard for a reason",
      "Actions and CI/CD integration is native and powerful",
      "Markdown rendering and documentation tools are excellent",
    ],
    weaknesses: [
      "Visual density can overwhelm new users",
      "Project management features feel bolted on",
      "Settings and permissions are spread across too many screens",
    ],
  },
  {
    name: "Spotify",
    slug: "spotify",
    url: "spotify.com",
    category: "Media",
    score: 3.5,
    verdict: "Discovery is strong but settings and library management lag behind",
    delta: -0.2,
    description: "Spotify's recommendation engine remains its strongest UX feature — Discover Weekly, Daily Mixes, and algorithmic playlists genuinely surface music people love. The listening experience itself is solid. The downward delta reflects increasing frustration with library management, settings buried behind too many taps, and podcast integration that clutters the music experience.",
    strengths: [
      "Discovery algorithms are best-in-class in any consumer app",
      "Listening experience across devices is seamless",
      "Collaborative playlists create genuine social value",
    ],
    weaknesses: [
      "Library management has regressed over recent updates",
      "Podcast integration clutters the music experience",
      "Settings and preferences are hard to find and configure",
    ],
  },
  {
    name: "Slack",
    slug: "slack",
    url: "slack.com",
    category: "SaaS",
    score: 3.4,
    verdict: "Feature bloat is winning the war against early simplicity",
    description: "Slack's early genius was making work communication feel casual and fast. That simplicity is eroding. Huddles, Canvas, Clips, Workflow Builder, and the growing app ecosystem have added capability at the cost of focus. The core messaging experience is still good, but finding anything in a busy workspace now requires learned navigation patterns that new users struggle with.",
    strengths: [
      "Core messaging is fast and well-designed",
      "Search is powerful when you know the syntax",
      "Integration ecosystem is unmatched in workplace tools",
      "Thread model manages conversation scale effectively",
    ],
    weaknesses: [
      "Feature additions outpacing design coherence",
      "Navigation complexity grows with workspace size",
      "Performance degrades in large organizations",
    ],
  },
  {
    name: "Netflix",
    slug: "netflix",
    url: "netflix.com",
    category: "Media",
    score: 3.4,
    verdict: "Content discovery peaked years ago — the UI hasn't kept up",
    description: "Netflix defined streaming UX but hasn't meaningfully evolved in years. The row-based browsing model still works, autoplay previews are polarizing, and the 'Continue Watching' row remains both the most useful and most neglected feature. The viewing experience is solid. The content discovery experience is coasting.",
    strengths: [
      "Playback experience is reliable across every device",
      "Profile system handles household sharing well",
      "Content metadata and categorization is rich",
    ],
    weaknesses: [
      "Autoplay previews remain controversial and disruptive",
      "Discovery UI hasn't meaningfully evolved in years",
      "Search results and recommendations increasingly feel random",
    ],
  },
  {
    name: "Loom",
    slug: "loom",
    url: "loom.com",
    category: "Productivity",
    score: 3.4,
    verdict: "Record-to-share in seconds — the core loop is pristine",
    description: "Loom's core interaction — record screen, get shareable link — is one of the tightest product loops in SaaS. Three clicks from thought to shared video. Where the score is held back: the viewing experience, organization of recorded content, and workspace management all feel like they were designed after the core recording feature shipped.",
    strengths: [
      "Recording-to-sharing flow is remarkably frictionless",
      "Viewer experience loads fast and works everywhere",
      "AI summaries and chapters add genuine value",
    ],
    weaknesses: [
      "Video organization and workspace management feel basic",
      "Editing capabilities are minimal",
      "Enterprise features feel grafted onto a consumer product",
    ],
  },
  {
    name: "Canva",
    slug: "canva",
    url: "canva.com",
    category: "Productivity",
    score: 3.3,
    verdict: "Template-first approach democratizes design at scale",
    description: "Canva solved a real problem: most people need to create visual content but can't use professional design tools. The template system, drag-and-drop editor, and brand kit features make that possible. The experience is friendly and approachable. What holds it back from a higher score is that power users quickly hit walls, and the editor can feel sluggish with complex designs.",
    strengths: [
      "Templates turn non-designers into capable creators",
      "Brand kit ensures visual consistency across teams",
      "Export options cover virtually every use case",
    ],
    weaknesses: [
      "Editor performance degrades with complex designs",
      "Power users hit capability ceilings quickly",
      "Pricing model pushes premium content aggressively",
    ],
  },
  {
    name: "Framer",
    slug: "framer",
    url: "framer.com",
    category: "Developer Tools",
    score: 3.3,
    verdict: "Creative power with a steep on-ramp for non-designers",
    description: "Framer has evolved from a prototyping tool into a genuine website builder that produces production-quality output. The visual editor is powerful, animations are impressive, and the published sites perform well. The gap: the learning curve is steep for anyone who isn't already a designer, and some common tasks require non-obvious interaction patterns.",
    strengths: [
      "Published sites are genuinely high-quality and fast",
      "Animation system is best-in-class for no-code tools",
      "Component system enables real reusability",
    ],
    weaknesses: [
      "Learning curve is steep for non-designers",
      "CMS capabilities still limited compared to purpose-built tools",
      "Pricing at scale can surprise teams",
    ],
  },
  {
    name: "Monzo",
    slug: "monzo",
    url: "monzo.com",
    category: "Fintech",
    score: 3.3,
    verdict: "Banking clarity that legacy institutions still can't match",
    description: "Monzo proved that banking apps don't have to feel like banking apps. Transaction categorization, instant notifications, and spending insights are presented with a clarity that makes legacy bank apps feel hostile by comparison. The experience falls short of higher levels because premium features are increasingly gated and the investment/savings products feel like different apps.",
    strengths: [
      "Transaction categorization and instant notifications",
      "Spending insights that actually change behavior",
      "Visual design that makes finance feel approachable",
    ],
    weaknesses: [
      "Premium feature gating creates a two-tier experience",
      "Investment and savings features feel disconnected",
      "International transfers still lag behind specialist tools",
    ],
  },
  {
    name: "Mercury",
    slug: "mercury",
    url: "mercury.com",
    category: "Fintech",
    score: 3.2,
    verdict: "Business banking that feels consumer-grade in the best way",
    description: "Mercury brought consumer-grade design to business banking — a category that historically looked like it was designed in 2005. Account management, transactions, and treasury features are clean and navigable. The score reflects that while the core banking experience is strong, some workflows (multi-entity management, complex permissions) still require too many steps.",
    strengths: [
      "Clean, modern interface for business banking",
      "Transaction management is fast and searchable",
      "API and integrations reflect developer-first thinking",
    ],
    weaknesses: [
      "Multi-entity management adds complexity",
      "Permission and role management could be simpler",
      "Limited international banking features",
    ],
  },
  {
    name: "Calendly",
    slug: "calendly",
    url: "calendly.com",
    category: "Productivity",
    score: 3.2,
    verdict: "The booking flow is flawless — everything around it is furniture",
    description: "Calendly's booker-facing experience is one of the best single-purpose flows in SaaS: see availability, pick a time, done. It's the gold standard for reducing a multi-step process to its minimum. The scheduler-facing dashboard, however, doesn't match that quality — event type management, team settings, and analytics all feel like they were designed with less care.",
    strengths: [
      "Booking flow is the gold standard for scheduling",
      "Calendar integrations are reliable and fast",
      "Customization options cover most use cases",
    ],
    weaknesses: [
      "Admin dashboard doesn't match the quality of the booking flow",
      "Team features add significant complexity",
      "Analytics and reporting are basic",
    ],
  },
  {
    name: "Pinterest",
    slug: "pinterest",
    url: "pinterest.com",
    category: "Consumer",
    score: 3.2,
    verdict: "Visual discovery remains best-in-class despite ad pressure",
    description: "Pinterest's masonry grid and visual search remain the best implementation of discovery-by-browsing on the web. The 'save to board' mental model is intuitive and sticky. What's pulling the score down: advertising is increasingly indistinguishable from organic content, and the balance between discovery and monetization is tilting toward the latter.",
    strengths: [
      "Visual discovery and browsing experience is unmatched",
      "Board organization is intuitive and flexible",
      "Visual search technology is genuinely useful",
    ],
    weaknesses: [
      "Ad content increasingly hard to distinguish from organic",
      "Mobile web experience pushes app installation aggressively",
      "Creator tools lag behind the consumer experience",
    ],
  },
  {
    name: "ChatGPT",
    slug: "chatgpt",
    url: "chatgpt.com",
    category: "Consumer",
    score: 3.1,
    verdict: "Conversational simplicity hides growing feature sprawl",
    description: "ChatGPT's core interaction — type a question, get an answer — is one of the most intuitive product experiences in recent memory. The blank input box is inviting. The problem is everything that's been added around it: GPTs, plugins, memory settings, model selection, file uploads, image generation. Each feature individually makes sense; together they're creating navigation complexity that undermines the original simplicity.",
    strengths: [
      "Core conversational interface is instantly intuitive",
      "Response formatting and code rendering are well-done",
      "Voice mode is genuinely impressive",
    ],
    weaknesses: [
      "Feature sprawl creating growing navigation complexity",
      "Model selection and capabilities are confusing for average users",
      "Conversation management and search are weak",
    ],
  },
  {
    name: "Robinhood",
    slug: "robinhood",
    url: "robinhood.com",
    category: "Fintech",
    score: 3.1,
    verdict: "Simplified investing with guardrails that sometimes patronize",
    description: "Robinhood succeeded at making investing feel approachable — the clean interface, confetti celebrations, and simplified flows brought millions of new investors into the market. The design challenge now is that those same simplifications can feel patronizing as users become more sophisticated, and the addition of crypto, options, and cash management has added complexity without proportional design investment.",
    strengths: [
      "Stock purchase flow is remarkably simple",
      "Portfolio visualization is clean and accessible",
      "Onboarding makes investing feel approachable",
    ],
    weaknesses: [
      "Oversimplification can feel patronizing to experienced users",
      "Risk communication could be more prominent",
      "Product additions haven't received equal design attention",
    ],
  },
  {
    name: "Webflow",
    slug: "webflow",
    url: "webflow.com",
    category: "Developer Tools",
    score: 3.0,
    verdict: "Immense power behind a UI that asks too much of newcomers",
    description: "Webflow is probably the most powerful no-code website builder available. It can produce genuinely professional websites with complex interactions, CMS-driven content, and e-commerce. The score reflects a tension: experts love it, beginners bounce. The learning curve is the product's biggest liability and its biggest moat.",
    strengths: [
      "Output quality rivals custom development",
      "CMS and e-commerce are genuinely production-grade",
      "Interaction and animation system is extremely powerful",
    ],
    weaknesses: [
      "Learning curve is among the steepest in no-code tools",
      "Interface density overwhelms new users",
      "Collaboration features lag behind competitors",
    ],
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    url: "coinbase.com",
    category: "Fintech",
    score: 2.9,
    verdict: "Onboarding is solid but the product grows confusing fast",
    delta: -0.3,
    description: "Coinbase's onboarding and initial purchase flow are clean — buying your first crypto is straightforward. The experience degrades from there. The addition of DeFi features, NFTs, staking, and Coinbase Wallet has created a product that serves too many audiences without a coherent experience for any of them. The downward delta reflects recent UI changes that added complexity without solving existing navigation problems.",
    strengths: [
      "Initial onboarding and first purchase are clean",
      "Security features are well-communicated",
      "Educational content is well-integrated",
    ],
    weaknesses: [
      "Product sprawl creating navigational confusion",
      "Fee structure is opaque and inconsistent",
      "Advanced and basic features uncomfortably coexist",
    ],
  },
  {
    name: "Airtable",
    slug: "airtable",
    url: "airtable.com",
    category: "SaaS",
    score: 2.9,
    verdict: "Spreadsheet flexibility with enterprise-grade confusion",
    description: "Airtable's pitch — a database that feels like a spreadsheet — is genuinely compelling when it works. Views, automations, and the interface designer enable powerful workflows. The problem: the gap between 'this is a nice spreadsheet' and 'this is a powerful app platform' creates confusion about what Airtable even is. Enterprise features have added layers that the core interaction model wasn't designed to support.",
    strengths: [
      "Core grid and view system is flexible and intuitive",
      "Automation builder is powerful for non-technical users",
      "Template marketplace enables fast starts",
    ],
    weaknesses: [
      "Identity crisis between spreadsheet and app platform",
      "Enterprise features add confusion for smaller teams",
      "Performance issues with large datasets",
    ],
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    url: "midjourney.com",
    category: "Consumer",
    score: 2.8,
    verdict: "Output quality masks an interface that's barely held together",
    description: "Midjourney produces the best AI-generated images available. The output is stunning. The interface — originally Discord-only, now a web app — is not. The web experience is functional but feels like it was designed by engineers solving technical problems rather than designers solving human ones. The score reflects that output quality and interface quality are two different things.",
    strengths: [
      "Image generation quality is best-in-class",
      "Prompt system rewards creativity and experimentation",
      "Community gallery provides inspiration and learning",
    ],
    weaknesses: [
      "Web interface feels technically functional, not designed",
      "Image management and organization are primitive",
      "Settings and preferences are scattered and confusing",
    ],
  },
  {
    name: "Discord",
    slug: "discord",
    url: "discord.com",
    category: "Consumer",
    score: 2.8,
    verdict: "Community power undermined by settings complexity",
    description: "Discord's core value — real-time community communication — is strong. Voice channels, text channels, and the server model create genuine community infrastructure. But the settings are bewildering: server settings, channel settings, notification settings, privacy settings, each with dozens of options. For a product used by millions of non-technical users, the configuration complexity is a serious accessibility issue.",
    strengths: [
      "Voice and text channel model is genuinely innovative",
      "Bot and integration ecosystem enables powerful automation",
      "Community features (forums, stages, events) are well-designed",
    ],
    weaknesses: [
      "Settings complexity is overwhelming",
      "Notification management requires expert-level configuration",
      "Onboarding to a new server is disorienting",
    ],
  },
  {
    name: "Zoom",
    slug: "zoom",
    url: "zoom.us",
    category: "SaaS",
    score: 2.7,
    verdict: "The core meeting is reliable — everything else feels bolted on",
    description: "Zoom's core meeting experience is reliable and familiar — that's its strength and its ceiling. Joining a meeting is easy. Being in a meeting works. Everything Zoom has added since — Zoom Phone, Zoom Whiteboard, Zoom Chat, Zoom Mail — feels like it belongs to a different product with a different design team. The experience is fragmented.",
    strengths: [
      "Meeting join flow is the simplest in the category",
      "Video and audio quality are reliable",
      "Screen sharing and recording are straightforward",
    ],
    weaknesses: [
      "Product additions feel disconnected from core experience",
      "Settings interface is overwhelming and outdated",
      "Desktop app feels bloated compared to web alternatives",
    ],
  },
  {
    name: "Twitch",
    slug: "twitch",
    url: "twitch.tv",
    category: "Media",
    score: 2.6,
    verdict: "Viewer experience is strong but creator tools are a maze",
    description: "Watching a stream on Twitch is a good experience — the player is solid, chat is engaging, and discovery has improved. Creating on Twitch is a different story. The creator dashboard, monetization settings, moderation tools, and analytics are spread across interfaces that feel like they were designed by different teams in different years. The viewer/creator gap is the defining UX problem.",
    strengths: [
      "Stream player and chat experience are well-integrated",
      "Discovery and recommendation have improved significantly",
      "Community features (raids, predictions) add engagement",
    ],
    weaknesses: [
      "Creator dashboard is fragmented and confusing",
      "Monetization settings require expert navigation",
      "Mobile experience trails desktop significantly",
    ],
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    url: "dropbox.com",
    category: "Productivity",
    score: 2.5,
    verdict: "The product that defined cloud storage now struggles to justify itself",
    description: "Dropbox invented a category and then watched the category commoditize around it. The core sync experience is still reliable, but the product has been unable to articulate why you'd choose it over Google Drive, iCloud, or OneDrive — which come free with products you already use. Recent additions (Paper, Capture, Sign) feel disconnected. The interface works; the product story doesn't.",
    strengths: [
      "File sync is still reliable and fast",
      "Shared folder collaboration is straightforward",
      "Desktop integration works well across platforms",
    ],
    weaknesses: [
      "Value proposition unclear against bundled competitors",
      "Product additions feel disconnected from core storage",
      "Pricing feels aggressive for what's offered",
    ],
  },
  {
    name: "Jira",
    slug: "jira",
    url: "atlassian.com/software/jira",
    category: "SaaS",
    score: 2.1,
    verdict: "More process than product — the UI serves the methodology, not the human",
    description: "Jira is powerful. Jira is also the canonical example of enterprise software that prioritizes process configuration over user experience. The interface serves Scrum and Kanban methodologies before it serves the humans using it. Every simple action — creating an issue, checking a sprint, finding a dashboard — requires more steps and more cognitive load than it should. Power at the cost of usability.",
    strengths: [
      "Configurability covers virtually any workflow",
      "Integration ecosystem is massive",
      "JQL query language is powerful for technical users",
    ],
    weaknesses: [
      "Every simple action requires too many steps",
      "Interface serves process methodology over humans",
      "Performance is sluggish for the complexity presented",
    ],
  },
  {
    name: "Salesforce",
    slug: "salesforce",
    url: "salesforce.com",
    category: "SaaS",
    score: 1.8,
    verdict: "Power under layers of UI debt that would take a decade to repay",
    delta: -0.1,
    description: "Salesforce is the most powerful CRM platform in the world and one of the worst user experiences in enterprise software. The Lightning redesign improved surface-level aesthetics but didn't address the fundamental information architecture problems. Navigation is labyrinthine, customization creates inconsistency, and the simplest tasks require too many clicks. Users don't choose Salesforce for its UX; they tolerate its UX for its capability.",
    strengths: [
      "Platform capability is genuinely unmatched in CRM",
      "AppExchange ecosystem extends into every business function",
      "Reporting and analytics are powerful once configured",
    ],
    weaknesses: [
      "Navigation is labyrinthine and inconsistent",
      "Customization creates experience fragmentation",
      "Simple tasks require too many clicks and page loads",
    ],
  },
  {
    name: "Workday",
    slug: "workday",
    url: "workday.com",
    category: "SaaS",
    score: 1.6,
    verdict: "Enterprise software that treats its users as an afterthought",
    description: "Workday is the product most people point to when they talk about why enterprise software has a bad reputation. The interface is functional in the strictest sense — you can complete tasks — but every interaction requires more effort than it should. Finding information requires memorizing navigation paths. Basic tasks like submitting time off or finding a pay stub involve more clicks than they do on any consumer app. The score reflects that users endure Workday; they don't use it.",
    strengths: [
      "Handles complex HR and finance workflows at enterprise scale",
      "Data model is comprehensive for large organizations",
      "Mobile app exists and covers basic tasks",
    ],
    weaknesses: [
      "Nearly every task requires more clicks than it should",
      "Navigation requires memorizing paths, not intuition",
      "Visual design is dated and information-dense without purpose",
    ],
  },
];

// Sort by score descending, assign ranks
export const PRODUCTS: Product[] = [...RAW_PRODUCTS]
  .sort((a, b) => b.score - a.score)
  .map((p, i) => ({ ...p, rank: i + 1 }));

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.category === product.category && p.slug !== product.slug
  ).slice(0, limit);
}

// Re-export from single source of truth
export { getScoreColor, getLevel } from "@/lib/ladder";
