import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Ladder",
  description: "Privacy Policy for Ladder by Drawbackwards.",
};

export default function PrivacyPage() {
  return (
    <div className="pt-32 pb-24 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-[2rem] font-bold mb-4">Privacy Policy</h1>
        <p className="text-sm text-muted mb-12">
          Last updated: March 28, 2026
        </p>

        <div className="space-y-10 text-sm text-body leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">Overview</h2>
            <p>
              This Privacy Policy explains how Drawbackwards LLC ("we", "us",
              "our") collects, uses, and protects your information when you use
              Ladder, including runladder.com, Ladder for Figma, Ladder for Claude,
              the Ladder API, and Ladder Pulse (collectively, the "Service").
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              What We Collect
            </h2>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Account information
            </h3>
            <p>
              When you create an account, we collect your name, email address, and
              authentication credentials through Clerk, our authentication
              provider. If you sign in with Google, we receive your name, email,
              and profile photo from Google.
            </p>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Content you submit
            </h3>
            <p>
              When you use the Service to score an interface, we receive the
              screenshots, URLs, or images you submit. We process this content
              through our AI scoring engine to generate your results.
            </p>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Scores and results
            </h3>
            <p>
              We store the scores, analyses, and recommendations generated by the
              Service, associated with your account if you are logged in.
            </p>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Usage data
            </h3>
            <p>
              We collect standard usage data including pages visited, features
              used, timestamps, browser type, device type, and IP address. This
              data helps us improve the Service.
            </p>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Payment information
            </h3>
            <p>
              Payment processing is handled by Stripe. We do not store your credit
              card number, bank account details, or other payment credentials.
              Stripe&apos;s privacy policy governs that data.
            </p>

            <h3 className="text-sm font-bold text-foreground mt-6 mb-2">
              Community votes
            </h3>
            <p>
              When you vote on a product score in the Top 100, we collect your vote
              value. Votes do not require an account and are anonymous.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              How We Use Your Information
            </h2>
            <ul className="space-y-2 ml-4">
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To provide, maintain, and improve the Service</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To generate scores, analyses, and recommendations</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To manage your account and subscription</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To communicate with you about your account or the Service</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To publish free-tier scores and content on runladder.com (see below)</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>To improve our scoring models and framework</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Public vs Private Scores
            </h2>
            <p>
              <strong className="text-foreground">Free tier:</strong> Scores
              generated on the free tier may be published on runladder.com,
              including in the Top 100, teardowns, blog posts, social media, and
              other promotional or educational materials. Submitted screenshots may
              also be displayed alongside published scores. We will not associate
              published scores with your personal identity unless you opt in.
            </p>
            <p className="mt-3">
              <strong className="text-foreground">Paid plans:</strong> Scores
              generated on Professional, Team, and Enterprise plans are private by
              default. We will not publish your scores, submitted content, or
              results without your explicit written consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Surfaces and Data Flow
            </h2>
            <p>
              Ladder operates across multiple surfaces. Here is how your data flows
              through each:
            </p>
            <ul className="mt-3 space-y-3 ml-4">
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>
                  <strong className="text-foreground">runladder.com:</strong>{" "}
                  Content is submitted directly to our servers. Screenshots may be
                  captured via our URL capture service.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>
                  <strong className="text-foreground">Ladder for Figma:</strong>{" "}
                  Selected frames are sent from the Figma plugin to our API for
                  scoring. We receive the image data but not your full Figma file.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>
                  <strong className="text-foreground">Ladder for Claude:</strong>{" "}
                  When you use the Ladder skill in Claude.ai, your prompt and any
                  attached images are processed by Anthropic and then sent to our
                  scoring API. Anthropic&apos;s privacy policy governs data within
                  Claude.ai conversations.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>
                  <strong className="text-foreground">Ladder API:</strong>{" "}
                  Developers send content directly to api.runladder.com.
                  API requests are authenticated with API keys tied to your account.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>
                  <strong className="text-foreground">Ladder Pulse:</strong>{" "}
                  Customer feedback data, support transcripts, and other signals
                  are ingested and processed to generate experience scores. This
                  data may contain personal information from your customers. You
                  are responsible for ensuring you have the right to share this
                  data with us.
                </span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Third-Party Services
            </h2>
            <p>We use the following third-party services to operate Ladder:</p>
            <ul className="mt-3 space-y-2 ml-4">
              <li className="flex items-start gap-2">
                <span className="text-muted mt-0.5">-</span>
                <span><strong className="text-foreground">Clerk</strong> for authentication</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-muted mt-0.5">-</span>
                <span><strong className="text-foreground">Stripe</strong> for payment processing</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-muted mt-0.5">-</span>
                <span><strong className="text-foreground">Anthropic Claude</strong> for AI-powered scoring</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-muted mt-0.5">-</span>
                <span><strong className="text-foreground">Vercel</strong> for hosting and deployment</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-muted mt-0.5">-</span>
                <span><strong className="text-foreground">Upstash</strong> for data storage</span>
              </li>
            </ul>
            <p className="mt-3">
              Each of these services has its own privacy policy governing its
              handling of your data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Data Retention
            </h2>
            <p>
              We retain your account information and score history for as long as
              your account is active. If you delete your account, we will delete
              your personal data within 30 days, except for scores that have
              already been published on the free tier (which are anonymized).
            </p>
            <p className="mt-3">
              Anonymous usage data and aggregated analytics may be retained
              indefinitely.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Data Security
            </h2>
            <p>
              We use industry-standard measures to protect your data, including
              encryption in transit (TLS) and at rest. However, no method of
              transmission or storage is 100% secure. We cannot guarantee absolute
              security.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">Your Rights</h2>
            <p>You may:</p>
            <ul className="mt-3 space-y-2 ml-4">
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>Access the personal data we hold about you</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>Request correction of inaccurate data</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>Request deletion of your account and associated data</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>Export your score history</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-ladder-green mt-0.5">+</span>
                <span>Opt out of marketing communications</span>
              </li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, contact us at{" "}
              <Link href="/contact" className="text-ladder-green hover:text-ladder-green/80 transition-colors">
                runladder.com/contact
              </Link>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">Cookies</h2>
            <p>
              We use essential cookies for authentication and session management.
              We may use analytics cookies to understand how the Service is used.
              We do not sell your data or use advertising cookies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">
              Children&apos;s Privacy
            </h2>
            <p>
              The Service is not intended for children under 13. We do not
              knowingly collect personal information from children under 13.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">Changes</h2>
            <p>
              We may update this Privacy Policy from time to time. Material changes
              will be communicated through the Service or by email. Continued use
              after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-3">Contact</h2>
            <p>
              Questions about this Privacy Policy? Reach us at{" "}
              <Link href="/contact" className="text-ladder-green hover:text-ladder-green/80 transition-colors">
                runladder.com/contact
              </Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
